# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 02:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('amount', models.IntegerField(max_length=10)),
                ('date', models.ImageField(max_length=15, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files_type', models.CharField(max_length=20)),
                ('input_title', models.CharField(max_length=20)),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Budget.Expense')),
            ],
        ),
    ]
