# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-25 22:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0003_auto_20170620_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='input',
            old_name='amount',
            new_name='expense',
        ),
    ]
