# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-25 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0004_auto_20170625_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
